function compareHRandT(X1, Y1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  time
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Mar-2015 16:31:33

% Create figure
figure1 = figure;

% Characteristics of plot
width = 4.5;     % Width in inches
height = 3;    % Height in inches
alw = 0.75;    % AxesLineWidth
fsz = 8;      % Fontsize
lw = 1.5;      % LineWidth
msz = 4;       % MarkerSize

pos = get(gcf, 'Position');
set(gcf, 'Position', [pos(1) pos(2) width*100, height*100]); %<- Set size

% Create subplot
subplot1 = subplot(2,1,1, 'XTick', zeros(1,0),'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
tnorm = X1-X1(1);
t = tnorm./60;

data1 = zeros(length(t),length(Y1)+1);
data1(:,1) = Y1(1).HR.HR_ref(X1(1)+1:X1(end)+1,1);
for i=1:length(Y1)
    data1(:,i+1) = Y1(i).HR.HR(X1(1)+1:X1(end)+1,1);
end

plot1 = plot(t,data1,'Parent',subplot1,'LineWidth',lw);
set(plot1(1),'DisplayName','HR_{REF}','Color',[0 0 0],'LineWidth',0.5);

a = cell(3,1);
a{1,1} = '-.';
a{2,1} = '-';
a{3,1} = '--';
for i=1:length(Y1)
    c = 0.5-(i-1)*0.1;
    set(plot1(i+1),'DisplayName', sprintf('%s_{%s}',Y1(i).HR.Name, Y1(i).CT),...
        'LineStyle',a{i,1},'Color',[c c c]);
end

% Create ylabel
ylabel('Heart rate [bpm]');
ylim([95 155])

% limit x-axes
xlim([t(1) t(end)])


% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to plot
data2 = zeros(length(t),length(Y1));
for i=1:length(Y1)
    data2(:,i) = Y1(i).T.T_M(X1(1)+1:X1(end)+1,1);
end


plot2 = plot(t,data2,'Parent',subplot2,'LineWidth',1);
for i=1:length(Y1)
    c = 0.5-(i-1)*0.2;
    set(plot2(i),'DisplayName', sprintf('%s_{%s}',Y1(i).T.Name, Y1(i).CT),...
        'LineStyle',a{i,1},'Color',[c c c]);
end

% Create xlabel
xlabel('Time [min]');
xlim([t(1) t(end)])

% Create ylabel
ylabel('Torque [Nm]');
ylim([0 20])

% Create legend
legend2 = legend(subplot2,'show');
set(legend2,...
    'Location', 'North', 'Orientation', 'horizontal',...
    'FontSize',8);

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Location', 'South', 'Orientation', 'horizontal',...
    'FontSize',8);

